### ISSUE TITLE
How to handle BACs that are identical within a assembled BAC? Leave one out???

### ISSUE THREAD

**Issue by suryasaha** [solgenomics/Bio-GenomeUpdate#47]
![selection_001_screenshot](https://cloud.githubusercontent.com/assets/1084749/7660514/bc8529b8-fb18-11e4-9e60-08f2a7f4d110.png)

Contig 469 for Chr 10 represented by the following TPF lines
AC244937	?	SL2.50sc05925	MINUS
AC244803	?	SL2.50sc05925	PLUS
AC244944	?	SL2.50sc05925	PLUS
AC254768	?	SL2.50sc05925	MINUS

Can be
AC244937	?	SL2.50sc05925	MINUS
AC244944	?	SL2.50sc05925	PLUS
AC254768	?	SL2.50sc05925	MINUS

**Comment by GenomeRef** [comment]
The Genome Reference Consortium (GRC) uses a minimal tiling path for the human, mouse and zebrafish reference genome assemblies wherever possible. The alignments of the redundant components are evidence for the path, but are not used in the assembly AGP. We would simplify the following:
AC244870	?	SL2.50sc05925 PLUS
AC254768	?	SL2.50sc05925 MINUS
AC244944	?	SL2.50sc05925 PLUS
AC244937	?	SL2.50sc05925 PLUS
AC244803       ?      SL2.50sc05925 MINUS

to this:
AC244870	?	SL2.50sc05925 PLUS
AC244937	?	SL2.50sc05925 PLUS

We only retain redundant components in an AGP if we explicitly want to use sequences from those components (e.g. to capture an indel or correct an error in another component). The contribution of each component (start/stop) to the final FASTA is explicit in the AGP.

**Comment by suryasaha** [comment]
Will not be done automatically. Create git repo for all TPF files for SL3.0. Remove redundant BACs using tpf_solo error messages and use commit messages to track the changes.

**Comment by suryasaha** [comment]
Using filter_group_coords_output.pl 9d7d8e2abf856fcf160318542287f869189a37ce to keep only one BAC or Contig BAC for a reference region.

WGS contigs (double) covered by 2 BACs will still cause `Critical: Overlapping switch points` errors. Will still need to manually go through ACE files for Contigs with redundant BACs and manually remove them from updated TPF.
