### ISSUE TITLE
Some reference and alt alleles are incorrect in vcfs mapped to build 2.50

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/Bio-GenomeUpdate#58]
From a user:

Dear SGN,

I am parsing the data from 360 genomes project. I've seen so far that some SNPs in the VCF files of SL2.50 have a wrong reference allele. For example, having the following list:

SL2.50ch01      39138511        G       C
SL2.50ch01      39141120        T       A
SL2.50ch01      39144494        G       C
SL2.50ch01      39162103        G       C
SL2.50ch01      39175764        G       C
SL2.50ch01      39177173        G       C
SL2.50ch01      39186267        G       C
SL2.50ch01      39192822        G       C
SL2.50ch01      39207130        G       C
SL2.50ch01      39207130        G       C

the first column is the chromosome name, the second column contains the position in the reference genome SL2.50, the third column is the reference allele in your VCF files, and the 4th column is actually the reference allele in SL2.50.

It does not happen in all SNPs, only in some of them. Why do I see so many transversions? Why did you choose different strands at the time of reporting your variants?

**Comment by bellerbrock** [comment]
It looks like my vcf update scripts only updated the physical coordinates from 2.40 to 2.50, and did not take into account the possibility of REF and ALT alleles changing when a particular contig is flipped and both the position and ref/alt allele change.

replying to the user now, and will have to fix update scripts and re-run them.

**Comment by suryasaha** [comment]
98f169ae58327c6bc726f391c0f8d631cb1e5284
