### ISSUE TITLE
ITAG gene naming for novel genes

### ISSUE THREAD

**Issue by phosmani** [solgenomics/Bio-GenomeUpdate#60]
Naming ITAG genes with Solyc ID convention. 
In ITAG3.0 there are several novel genes compared to ITAG2.40 which needs Solyc ID. In general, the ID should reflect chromosome number and genomic position.  

Conditions
-conflict with any previous Solyc ID

**Comment by suryasaha** [comment]
Does not handle Solyc ids in cases where > 9 genes are added between 2 Solyc ids. Just puts a placeholder for now.

**Comment by suryasaha** [comment]
Novel genes should have ids starting in the middle of the interval

Nof genes | Number
------------ | -------------
1 | 15
2 | 13,17
3 | 13,15,17
4 | 12,14,16,18
5 | 11,12,14,16,18
6 | 11,12,13,14,16,18
7 | 11,12,13,14,15,16,18
8 | 11,12,13,14,15,16,17,18
9 | 11,12,13,14,15,16,17,18,19

**Comment by phosmani** [comment]
chromosome 7 issue. Novel gene ID assignment for first genes at the start of chromosome. There are 3 novel genes before old Solyc ID comes up. First one got correct assignment (Alias=Solyc07g004991). But next two genes gives error.
Error: 
Parsing GFF3 line 15 of 33349 to count novel genesUse of uninitialized value $prev_mRNA_ITAG24_Solycid in exists at /home/prashant/tools/Bio-GenomeUpdate/scripts/update_maker_names_gff_hard_coded.pl line 113.
Use of uninitialized value $prev_mRNA_ITAG24_Solycid in hash element at /home/prashant/tools/Bio-GenomeUpdate/scripts/update_maker_names_gff_hard_coded.pl line 118.
Parsing GFF3 line 25 of 33349 to count novel genesUse of uninitialized value $prev_mRNA_ITAG24_Solycid in exists at /home/prashant/tools/Bio-GenomeUpdate/scripts/update_maker_names_gff_hard_coded.pl line 113.
Use of uninitialized value $prev_mRNA_ITAG24_Solycid in hash element at /home/prashant/tools/Bio-GenomeUpdate/scripts/update_maker_names_gff_hard_coded.pl line 115.

**Comment by suryasaha** [comment]
Using hard coded intervals. Need to automate the namespace distribution
39c2d19ed79ac068834bed4493ea487966640886

**Comment by suryasaha** [comment]
9964e0b77cf9a38b4a9001168014fe343cf0726c
