### ISSUE TITLE
Assigning Solyc from ITAG2.40 to ITAG2.90

### ISSUE THREAD

**Issue by phosmani** [solgenomics/Bio-GenomeUpdate#61]
In two steps
1. Assign Solyc ID from maker updated ITAG2.43 annotation set based on blastp output.
            -- check if the blastp match SolycID is in order as per ITAG2.40.
2. Replace maker generated names with Solyc ID from Name field within gff attributes column.

GFF file with MAKER names and ITAG names.
/export/projects/SL3.0/ITAG3.0/ITAG2.90/ITAG2.90_standard.gff

TAB delimited file for ID conversion.
 /export/projects/SL3.0/ITAG3.0/ITAG2.90/ITAG_pass_standard.id.map

**Comment by phosmani** [comment]
3' UTR has not been assigned proper ID.
SL3.0ch00       maker   three_prime_UTR 551576  551581  .       +       .       ID=five_prime_UTR:Solyc00g005040.2.1.0;Parent=mRNA:S

**Comment by suryasaha** [comment]
intron GFF rows need to be added

**Comment by suryasaha** [comment]
Not adding intron rows

**Comment by phosmani** [comment]
passing names from Alias is leading to redundant names to genes. There are ~700 cases which have redundant names.

**Comment by phosmani** [comment]
mRNA line does not have parent ID for its corresponding gene.

**Comment by suryasaha** [comment]
Novel genes should have ids starting in the middle of the interval

Nof genes | Number
------------ | -------------
1 | 15
2 | 13,17
3 | 13,15,17
4 | 12,14,16,18
5 | 11,12,14,16,18
6 | 11,12,13,14,16,18
7 | 11,12,13,14,15,16,18
8 | 11,12,13,14,15,16,17,18
9 | 11,12,13,14,15,16,17,18,19

**Comment by suryasaha** [comment]
b1359531e8b1c66db9183ccd8e25dda9ad5a7c8a
